const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_18_06_10_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAyMzksXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMjgsXG4gICAgICAgIDI0LFxuICAgICAgICAyMDksXG4gICAgICAgIDExMCxcbiAgICAgICAgNTgsXG4gICAgICAgIDExNCxcbiAgICAgICAgODUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgNixcbiAgICAgICAgMTMxLFxuICAgICAgICAzOCxcbiAgICAgICAgMTc4LFxuICAgICAgICAxMDYsXG4gICAgICAgIDYwLFxuICAgICAgICA5NyxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNjEsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjcsXG4gICAgICAgIDM0LFxuICAgICAgICAyMzEsXG4gICAgICAgIDMxLFxuICAgICAgICAxNjUsXG4gICAgICAgIDEzLFxuICAgICAgICAxNDksXG4gICAgICAgIDE3MCxcbiAgICAgICAgNDYsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExLFxuICAgICAgICAyNDUsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTYsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTE4LFxuICAgICAgICA5NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDg2LFxuICAgICAgICAzNCxcbiAgICAgICAgNTgsXG4gICAgICAgIDEsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTcyLFxuICAgICAgICA2NyxcbiAgICAgICAgMTc3LFxuICAgICAgICA2MCxcbiAgICAgICAgNTIsXG4gICAgICAgIDEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNDQsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjExLFxuICAgICAgICA4OCxcbiAgICAgICAgMTk2LFxuICAgICAgICA2MyxcbiAgICAgICAgMTMxLFxuICAgICAgICA2OSxcbiAgICAgICAgODdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQwLFxuICAgICAgICAxOSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMSxcbiAgICAgICAgNjYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjEsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTI2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDY0LFxuICAgICAgICA4OSxcbiAgICAgICAgNDIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjE5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTE4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMjksXG4gICAgICAgIDM3LFxuICAgICAgICA5MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjQsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxNCxcbiAgICAgICAgMjM3LFxuICAgICAgICA1OSxcbiAgICAgICAgOTEsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTY5LFxuICAgICAgICA4MyxcbiAgICAgICAgMTY2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNjcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNjgsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTYxLFxuICAgICAgICAxODYsXG4gICAgICAgIDU2LFxuICAgICAgICA5NSxcbiAgICAgICAgMjI0LFxuICAgICAgICAxMTksXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTg2LFxuICAgICAgICAxOTcsXG4gICAgICAgIDk0LFxuICAgICAgICAxOTMsXG4gICAgICAgIDEyMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjksXG4gICAgICAgIDEyMixcbiAgICAgICAgMTQ0LFxuICAgICAgICA2MSxcbiAgICAgICAgMTEsXG4gICAgICAgIDYyLFxuICAgICAgICAyLFxuICAgICAgICAwLFxuICAgICAgICAxODIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMzEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNzQsXG4gICAgICAgIDIxNyxcbiAgICAgICAgNTUsXG4gICAgICAgIDc0LFxuICAgICAgICAyLFxuICAgICAgICAxMixcbiAgICAgICAgMTYwLFxuICAgICAgICAzMixcbiAgICAgICAgMTIyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNTksXG4gICAgICAgIDg3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0MixcbiAgICAgICAgMTEyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDE3LFxuICAgICAgICA1NSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxNTgsXG4gICAgICAgIDExLFxuICAgICAgICAxMzcsXG4gICAgICAgIDE3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjI2LFxuICAgICAgICAyMjksXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDMwLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNjAsXG4gICAgICAgIDM1LFxuICAgICAgICA4MCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAzLFxuICAgICAgICAxNDMsXG4gICAgICAgIDEwLFxuICAgICAgICA3OSxcbiAgICAgICAgNyxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMzksXG4gICAgICAgIDE3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE2LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDkzXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjMsXG4gICAgICAgIDE4LFxuICAgICAgICAxLFxuICAgICAgICA5MyxcbiAgICAgICAgMTAwLFxuICAgICAgICAyMjAsXG4gICAgICAgIDgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTI4LFxuICAgICAgICAyOSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDEzMixcbiAgICAgICAgNixcbiAgICAgICAgMTg4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDMzLFxuICAgICAgICAxMzksXG4gICAgICAgIDIsXG4gICAgICAgIDExNCxcbiAgICAgICAgNDksXG4gICAgICAgIDEzNSxcbiAgICAgICAgOTIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDk1LFxuICAgICAgICA5NCxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDExLFxuICAgICAgICA4MSxcbiAgICAgICAgMTYwLFxuICAgICAgICAxNzksXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNDQsXG4gICAgICAgIDQsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjMzLFxuICAgICAgICAxMDEsXG4gICAgICAgIDkxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjA2LFxuICAgICAgICAxOTIsXG4gICAgICAgIDEwLFxuICAgICAgICAxNjUsXG4gICAgICAgIDM0LFxuICAgICAgICAxNTksXG4gICAgICAgIDE5MCxcbiAgICAgICAgOTAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNTcsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjE4LFxuICAgICAgICAxMzJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE0NCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIxYkVzNmloWitPTVgrQXF5aDB2am9xazJ4Ymo1VWlLbkd5ZzVPQk5BdFo0PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJBRV9CZlluN1FkaS1PNHR3ZmNqQkJRXCIsXG4gIFwicGhvbmVJZFwiOiBcImZmOTc2MjMzLWE3NGEtNGQzYS05MWQxLTYyNDAzMTRjZTI5ZFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA2NyxcbiAgICAgIDM0LFxuICAgICAgNjIsXG4gICAgICA1OCxcbiAgICAgIDUyLFxuICAgICAgOTcsXG4gICAgICAyMDEsXG4gICAgICAxNDUsXG4gICAgICA0NSxcbiAgICAgIDE0MSxcbiAgICAgIDU4LFxuICAgICAgMTY3LFxuICAgICAgMTk2LFxuICAgICAgMTE5LFxuICAgICAgMTU0LFxuICAgICAgMTMsXG4gICAgICAxMzEsXG4gICAgICAxMjUsXG4gICAgICAxNTcsXG4gICAgICAyMzJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTc2LFxuICAgICAgMTIwLFxuICAgICAgNzgsXG4gICAgICAyNTQsXG4gICAgICAxMjMsXG4gICAgICAxOTgsXG4gICAgICAyMTIsXG4gICAgICAxOTEsXG4gICAgICAzMSxcbiAgICAgIDE0NSxcbiAgICAgIDMsXG4gICAgICAyNSxcbiAgICAgIDE5NSxcbiAgICAgIDEyNSxcbiAgICAgIDE0LFxuICAgICAgMjI4LFxuICAgICAgMjIxLFxuICAgICAgOTAsXG4gICAgICAyNDAsXG4gICAgICAyNTNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiTkVSVjQ1SE5cIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NDcxMDgxOTQ5MTo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyMDExOTgxMTIxMDg1NzI6NUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNJNkVzZDBCRUtuZjlMZ0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInRKTGFacDEzaVE3SGN0UEtnc0tUMGY4UTZPV0lQV0R0dnpFVjNqV2JseWc9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiaittNkluUUlMSDJNVkhucGNUcG9OVXdaM0hsbzdMUmsrOUcwSmlSZ1VteTZ1TFhGejZ2N0ZteVV0c2pXcXV1SkxrZ01XTEFpKzEyc0tmd2x0MkdsQlE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiTUZqcVV5NzJ1YlVnL0M4MFBuRTVwSzhlT0RHTjZLTHhjdXJtVkZnQ3RjSTIxS3cxaGRXNjJpVm1lQWhIYkFuOWZQckcyZnhCWGFlQkd3dHFabzFBakE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU0NzEwODE5NDkxOjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICA0MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5OTY1OTk4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBUHRSXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQdFIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxMUl4SC8vWEdzTEFOTzlpRGxJeU1wOTdBVDhyQXh1Q3hZSmNmSmQ4YjA4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjQ2NDI3MzkzNCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI5OTY2MDAyMDgwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
